---
apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: stub
spec:
  credentials:
    secretRef:
      key: instanceCredentials
      name: grafana-instance
      namespace: crossplane
    source: Secret
  oncallUrl: https://oncall-ops-eu-south-0.grafana-ops.net/oncall/
  smUrl: https://synthetic-monitoring-api-eu-south-0.grafana-ops.net
  url: https://ops.grafana-ops.net
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-instance
  namespace: crossplane
type: Opaque
data:
  instanceCredentials: <redacted>
