---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-grafana-data
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: function-grafana-data
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.9.1@sha256:9d337903fd62a03dbdb9edfbc2c7f2029554ef81834fd520efd6080575c0b1cc
